services:
  kruzinator-vue-dev:
    build:
      context: kruzinator-vue
      dockerfile: Dockerfile.dev
    # ...
    develop:
      # Create a `watch` configuration to update the app
      #
      watch:
        # Sync the working directory with the `/app` directory in the container
        - action: sync
          path: kruzinator-vue/
          target: /app
          # Exclude the project dependencies from being synced
          ignore:
            - node_modules/

        # Rebuild the image on changes to the `package.json` or `package-lock.json` files
        - action: rebuild
          path: kruzinator-vue/package.json
    labels:
      - traefik.enable=true
      - traefik.http.routers.kruzinator-vue-dev.rule=Host(`dev.kruzinator.capturemyhand.com`)
      - traefik.http.routers.kruzinator-vue-dev.entrypoints=websecure
      - traefik.http.routers.kruzinator-vue-dev.tls.certresolver=tlschallenge
    networks:
      - web

  kruzinator-api-dev:
    build:
      context: kruzinator-api
      dockerfile: Dockerfile
      args:
        UV_NO_DEV: 0
        UV_COMPILE_BYTECODE: 1
    # ...
    depends_on:
      kruzinator-postgres:
        condition: service_healthy
    develop:
      # Create a `watch` configuration to update the app
      #
      watch:
        # Sync the working directory with the `/app` directory in the container
        - action: sync
          path: kruzinator-api/
          target: /app
          # Exclude the project virtual environment
          ignore:
            - kruzinator-api/.venv/

        # Rebuild the image on changes to the `pyproject.toml`
        - action: rebuild
          path: kruzinator-api/pyproject.toml
    labels:
      - traefik.enable=true
      - traefik.http.routers.kruzinator-api-dev.rule=Host(`dev.kruzinator.capturemyhand.com`) && (PathPrefix(`/api`) || Path(`/openapi.json`) || Path(`/docs`) || Path(`/redoc`))
      - traefik.http.routers.kruzinator-api-dev.entrypoints=websecure
      - traefik.http.routers.kruzinator-api-dev.tls.certresolver=tlschallenge
      - traefik.http.services.kruzinator-api-dev.loadbalancer.server.port=8000
    environment:
      - PORT=8000
      - SESSION_DATA_PATH=/data/sessions
    networks:
      - web
      - default

  kruzinator-postgres:
    image: postgres:18
    environment:
      - POSTGRES_DB=kruzinator
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d kruzinator"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
  kruzinator-seaweedfs:
    image: "chrislusf/seaweedfs:4.15_large_disk"
    entrypoint: "weed"
    command: mini -dir=/data -ip=127.0.0.1 -ip.bind=0.0.0.0
    environment:
      AWS_ACCESS_KEY_ID: seaweedfs
      AWS_SECRET_ACCESS_KEY: seaweedfs
    healthcheck:
      test: [
          "CMD-SHELL",
          # Manually override any http_proxy envvar that might be set, because
          # this wget does not support no_proxy. See:
          # https://github.com/getsentry/self-hosted/issues/1537
          "http_proxy='' wget -q -O- http://kruzinator-seaweedfs:8080/healthz http://kruzinator-seaweedfs:9333/cluster/healthz http://kruzinator-seaweedfs:8333/healthz || exit 1",
      ]
      interval: 30s
      timeout: 20s
      retries: 5
      start_period: 60s
    labels:
      - traefik.enable=true
      - traefik.http.routers.kruzinator-filer-seaweedfs.rule=Host(`dev.filer.kruzinator.capturemyhand.com`)
      - traefik.http.routers.kruzinator-filer-seaweedfs.entrypoints=websecure
      - traefik.http.routers.kruzinator-filer-seaweedfs.tls.certresolver=tlschallenge
      - traefik.http.services.kruzinator-filer-seaweedfs.loadbalancer.server.port=8888
    volumes:
      - ./data/seaweedfs:/data
    networks:
      - web
      - default

networks:
  web:
    external: true
      